### ISSUE TITLE
Not Booting in Raspberry Pi 4

### ISSUE THREAD

**Issue by actraiser30** [neilmunday/pes#41] opened 2019-08-24 16:47 UTC
Hello, i tried today the latest pes version 2,7 for the Raspberry pi 4 (1GB version)
after resizing partition its not booting the Gui it stucks in the operations completed successfully message,after i remove the power and put it back it stucks in the starting pes message
i tried the image in the Raspberry pi 3B and works fine

is this a known bug on the Rpi 4?

Thanks

**Comment by neilmunday** [comment] 2019-08-25 19:02
Hi @actraiser30. I have to confess that I have not been able to test PES on a Raspberry Pi 4 as I do not have access to one. However, the firmware that comes with Arch Linux should work with the Raspberry Pi 4.

As you have a RPi 4, can you try this for me please?

1. Boot your RPi 4.

2. Connect a keyboard to your RPi 4 or SSH in.

3. If using a keyboard, press "Ctrl + C" to kill the PES GUI.

Now if using a keyboard or SSH, run the command `ps -aef | grep python`. Take a note of the process ID (left hand column) of any Python processes that reference the PES GUI and for each one run: `kill -9 PROCESS_ID` where `PROCESS_ID` is the number of the process.

4. At this point there should be no PES prcesses running. You can confirm this by re-rerunning: `ps -aef | grep python`.

5. Now launch PES in debug mode: `/opt/pes/bin/pes -v`

6. Please share with me the output. Does the GUI load at all?

**Comment by actraiser30** [comment] 2019-08-31 07:30
Hi sorry for the delay,i cannot kill the gui i have a mini usb keyboard/mouse and the Ctrl + C does not seem to do anything,i dont have a normal keyboard to check it.also the | symbol is not working in my keyboard,im afraid you need to find an Rpi 4 and do it your self

**Comment by actraiser30** [comment] 2019-08-31 09:01
i also managed to update the firmware and switch it to raspberrypi4 but still stucks in loading
arch linux must be the problem,is there a way to install pes to raspbian buster lite?

thanks

**Comment by neilmunday** [comment] 2019-08-31 09:17
Creating a Raspbian version of PES would take a lot of time and effort. 

A friend is kindly lending me his Raspberry Pi 4 next week so hopefully I will be able to work out what the problem is.

**Comment by neilmunday** [comment] 2019-09-05 20:02
I've now been able to repeat the issue. It would appear that since the Raspberry Pi 4 has been released, the ArchLinux Arm site has now produced a separate Raspberry Pi 4 image rather than using the Raspberry Pi 2 image (as advised originally). I will therefore have to create an image from scratch for the Raspberry Pi 4.

**Comment by neilmunday** [comment] 2019-09-06 20:31
After doing some further reading, the Raspberry Pi 4 does not use the closed source VC4 driver (usually found under `/opt/vc`). Instead the  the open source vc4-fkms-v3d driver should be used instead. I'm trying to get this working.

**Comment by neilmunday** [comment] 2019-09-10 22:11
Status update...

- [X] PES GUI (now at version 2.8)
- [X] Vice Emulator (standalone C64)
- [ ] Retroarch: compiled but very poor performance - trying to work out why
- [ ] Mupen64plus (standalone N64): to be done

**Comment by neilmunday** [comment] 2019-09-23 20:00
Unable to compile PPSSPP at the moment. Issue raised at: https://github.com/hrydgard/ppsspp/issues/12346

PES 2.8 (BETA) for the Raspberry Pi 4 will be released without this emulator for now.

**Comment by neilmunday** [comment] 2019-09-23 22:07
PES 2.8 BETA image for the Raspberry Pi 4 can be found at: http://www.mundayweb.com/pes/pes-2.8-BETA-2019-09-23-rpi4.img.gz.torrent

**Comment by neilmunday** [comment] 2019-09-24 21:20
[Direct download](https://pes.neilmunday.co.uk/download.php?system=rpi4) (md5sum: a95a8c848f86c04dfcf958355c9e21ac, 1.3GB) now available.

**Comment by neilmunday** [comment] 2019-10-05 22:51
@actraiser30 have you tried out the image?

**Comment by neilmunday** [comment] 2019-10-18 20:04
Closing, PES 2.8 BETA for RPi 4 released as above.

**Closed by neilmunday** 2019-10-18 20:04 UTC
Labels: ArchLinux, help wanted
